# Site settings
baseurl = "https://baumannzone.github.io/hugo-playing/"
publishDir = "docs"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Playing with Hugo - Baumannzone"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-60085396-7"
hasCJKLanguage = false

[params]
	name = "Jorge Baumann"
	description = "Playing with Hugo, static site generator"
	bio = "Playing with Hugo"
	# Enter optionally your twitter account
	twitter = "https://twitter.com/baumannzone"
	enableRSS = false

	# Disqus comment
	disqusShortname = "playing-with-hugo"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
    terminal = "your_facebook_link"
    twitter-square = "https://twitter.com/baumannzone"
    github-square = "https://github.com/baumannzone"
